-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4eLiA5WL+dYJIvKw
cWVJ+qc016PJBBaAQkc5HQ5Aq1SgCgYIKoZIzj0DAQehRANCAATeWrFecwRhzCM2
P6RBmdvrzXhVBNU1e4xgVxRQnCxUb58v9vDeaBOH7UYnYmGcxIpWVgAE/nTzJwDZ
rVJDcmDE
-----END PRIVATE KEY-----